### PR TITLE
styles/32-change-gloabalcss-naming-convention-to-bem-standard

### PR DESCRIPTION
**Pull request by xzci**
- update two files 'global.css' and 'index.tsx'

### Descriptions

- Link to UI design (if possible):

### Provide screenshots of no warning, or error in the console.

- [X] All unit tests passing and coverage of testing is more than 90% unless special needs.
- [X] No merge conflict with the `main` branch, make sure your code is up to date with `main`.
- [X] Check PR title is aligned with your ticket.
- [X] Check your app will run without crashes.
- [X] Check if there are hard-coded values.
- [X] No `//eslint-disable-next-line no-unused-vars`, unless otherwise specified.
- [X] Check you are using `camelCase && PascalCase` correctly.
- [X] Remove unused comments.

### CODE REVIEW

**Comment by xzci** [comment]
image

**Comment by Cameron933** [comment]
Plz move the "font" folder into the styles folder like we discussed during stand-up meeting.

**Comment by Cameron933** [comment]
1. The naming of this Pull Request is not good, try to include the Zenhub card No.
2. The name of this branch is inappropriate. Please refer to the Example in readme file.

**Review by Cameron933 — APPROVED** [review]
LGTM

**Comment by ph0802** [comment]
All good.

**Review by ph0802 — APPROVED** [review]
All good.

**Pull request merged**
