### PR TITLE
132-current-testing-file-have-no-100-coverage

### PR DESCRIPTION
**Pull request by Prom1s1ngYoung**
### Descriptions

- Link to UI design (if possible):

### Provide screenshots or videos that the function is working.
image

### Provide screenshots of no warning, or error in the console.

- [x] All unit tests passing and coverage of testing is more than 90% unless special needs.
- [x] No merge conflict with the `main` branch, make sure your code is up to date with `main`.
- [x] Check PR title is aligned with your ticket.
- [x] Check your app will run without crashes.
- [x] Check if there are hard-coded values.
- [x] No `//eslint-disable-next-line no-unused-vars`, unless otherwise specified.
- [x] Check you are using `camelCase && PascalCase` correctly.
- [x] Remove unused comments.

### CODE REVIEW

**Review by HarryuCATGREY — COMMENTED** [review]
LGTM

**Review by Trent1900 — COMMENTED** [review]
LGTM

**Review by Trent1900 — APPROVED** [review]

**Comment by Prom1s1ngYoung** [comment]
> I want to recheck the test, I checkout this branch, and found: image Can you recheck your code?

I have checked the code, it is good in my local env.

**Review by tatoMa — APPROVED** [review]
Nice work. LGTM

**Pull request merged**
