### PR TITLE
Feat : add hook useMediaQuery

### PR DESCRIPTION
**Pull request by Trent1900**
### Descriptions

- Link to UI design (if possible):

### Provide screenshots or videos that the function is working.
image

### Provide screenshots of no warning, or error in the console.

- [x] All unit tests passing and coverage of testing is more than 90% unless special needs.
- [x] No merge conflict with the `main` branch, make sure your code is up to date with `main`.
- [x] Check PR title is aligned with your ticket.
- [x] Check your app will run without crashes.
- [x] Check if there are hard-coded values.
- [x] No `//eslint-disable-next-line no-unused-vars`, unless otherwise specified.
- [x] Check you are using `camelCase && PascalCase` correctly.
- [x] Remove unused comments.

how to use this custom Hook:
find BlogTitle.tsx file. then replace the file with 
```tsx
import styles from "./BlogTitle.module.css";
import { fontSyne, fontSatoshi } from "@/pages/_app";
import Button from "../base/Button";
import useMediaQuery from "@/hooks/useMediaQuery";
import EViewPortQuery from "@/constants/viewPortSize";
import { useEffect } from "react";

const { DESKTOP, TABLET, PHONE } = EViewPortQuery;

const BlogTitle = () => {
 
   let isDesktopSize = useMediaQuery(DESKTOP);
   console.log(isDesktopSize);
  return (
    <section className={styles["blog_title"]}>
      <h1
        className={`
        ${fontSyne.className} 
        ${!isDesktopSize ? "global__uppercase-heading-h2" : "global__heading--medium"} 
        ${styles["blog_title__title"]} 
        `}
      >
        Blog
      </h1>
      <div className={styles["blog_title__sub_title"]}>
        <div
          className={`${fontSatoshi.className} global__text-xlarge ${styles["blog_title__sub_title__text"]}`}
        >
          Discover, learn, and be inspired <br />
          with our blog.
        </div>
        <div className={styles["blog_title__sub_title__button_group"]}>
          <Button variant="secondary" isBlock={true}>
            VIDEO
          </Button>
          <Button variant="secondary" isBlock={true}>
            BRANDING
          </Button>
          <Button variant="secondary" isBlock={true}>
            DESIGN
          </Button>
        </div>
      </div>
    </section>
  );
};

export default BlogTitle;
```
`npm run dev` then, go to `http://localhost:3000/blog` and check the console. modify the constant`EViewPortQuery`/adjust the screen responsive to test the result.

### CODE REVIEW

**Review by HarryuCATGREY — COMMENTED** [review]
LGTM

**Review by HarryuCATGREY — COMMENTED** [review]
LGTM

**Comment by Charles-Xing** [comment]
The hook works, already tested

**Comment by Charles-Xing** [comment]
> how to use this custom Hook:
> find BlogTitle.tsx file. then replace the file with
> very sweet help from Trent(maybe need add another two files in local repo: constants/viewPortSize.ts  & hooks/useMediaQuery.ts)

**Review by Charles-Xing — APPROVED** [review]

**Pull request merged**
